title: Bangz Forge
description: join me
theme: just-the-docs

# URL settings (important for GitHub Pages)
url: "https://dxbangz.github.io"   # change to your site URL
#baseurl: "/my-docs"                     # repository name if using project site

# Navigation
#aux_links:

# Color scheme (light/dark)
color_scheme: dark

# Search
search_enabled: true
search.heading_level: 3
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10

# Footer
footer_content: "Copyright &copy; 2026 Bangz Forge."
